name: CMake CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake (all OS)
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.25.x'

      - name: Show tool versions
        run: |
          cmake --version
          python --version || true

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev ninja-build

      - name: MSVC dev env (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Ensure Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja || true

      # Configure
      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DGLFW_BUILD_EXAMPLES=OFF \
            -DGLFW_BUILD_TESTS=OFF \
            -DGLFW_BUILD_DOCS=OFF \
            -DGLFW_INSTALL=OFF

      # Build
      - name: Build
        run: cmake --build build --parallel
